name: ECS production deployment
env:
  BASE_API: ${{ secrets.BASE_API }}
on:
  push:
    branches:
      - main
jobs:
  ci-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run linters
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit
      - name: Run integrations tests
        run: yarn test:integration

  # cd-production:
  #   runs-on: ubuntu-latest
  #   needs: ci-production
  #   steps:
  #     - name: config aws credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
  #         aws-region: us-east-2
  #     - name: Get task definition
  #       run: aws ecs describe-task-definition --task-definition task-poke-api --query taskDefinition > task-definition.json
  #     - name: Fill in the new image ID in the Amazon ECS task definition
  #       id: task-def
  #       uses: aws-actions/amazon-ecs-render-task-definition@v1
  #       with:
  #         task-definition: task-definition.json
  #         container-name: poke-api
  #         image: aurigod/pokeapi:latest
  #     - name: Deploy aws ECS task definition
  #       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  #       with:
  #         task-definition: ${{ steps.task-def.outputs.task-definition }}
  #         service: service-poke-api
  #         cluster: cluster-pokemon-api
  #         wait-for-service-stability: true
